name: Build and Deploy App

on:
  push:
    branches:
      - main
   workflow_dispatch:

jobs:
  build_app:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: 3.16.4
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter tests
        run: flutter test

      - name: Build Flutter APK (release)
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        uses: w9jds/firebase-action@v2
        with: 
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
                --app com.example.demo_app \
                --groups "testers" \
                --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
