  name: Build and deploy
  
  on:
    push:
      branches:
        - main
  jobs:
    Build_app:
      runs-on: windows-latest
      steps:
      - name: Setup Flutter
        with:
          flutter-version: 3.16.4
          channel: stable
          cache: true
        uses: subosito/flutter-action@master
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Build APK (Release)
        run: flutter build apk --release
      - name: Deploy to firebase app distribution
        uses: w9dj/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/apk/release/app-release.apk \
                --app com.example.demo_app \
                --groups "testers"
                --token ${{ secrets.FIREBASE_SERVICE_ACCOIUNT}}   
