  name: Build and deploy
  
  on:
    push:
      branches:
        - main
  jobs:
    Build_app:
      runs-on: windows-latest
      steps:
      - name: Setup Flutter
        with:
          flutter-version: 3.16.4
          channel: stable
          cache: true
        uses: subosito/flutter-action@v2
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Install Flutter Dependencies
        run: flutter pub get
      - name: Build APK (Release)
        run: flutter build apk --release
      - name: Install Firebase tools for windows
        run: npm i -g firebase-tools@latest
      - name: Deploy APK (Windows)
        shell: pwsh
        run: cmd.exe /c "firebase appdistribution:distribute build/app/outputs/apk/release/app-release.apk --app com.example.demo_app --groups testers --token $env:FIREBASE_SERVICE_ACCOUNT"
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}